- name: seed-data
  hosts: cipui
  become: yes # Run tasks with root privileges

  vars:
    log_file: "{{ lookup('env', 'LOG_FILE').split(',') | first}}"
    comm_config_file: "{{ lookup('env', 'CONFIG_FILE').split(',') | first}}"
    demo_type: "{{ lookup('env', 'DEMO_TYPE').split(',') | first}}"
    installer_path: "{{ lookup('env', 'INSTALLER_PATH').split(',') | first}}"
    
  tasks:
  
    - name: Load Global parameters
      include_vars:
        file: "{{ item }}"
      with_items:
        - "{{ comm_config_file }}"
        - "{{ installer_path }}/cip_setup_automation.yml"
        - "../QueryIT/config-params.yml"

    - name: Log step
      lineinfile:
        path: "{{ log_file }}"
        line: |
          => Copying Seed Data Tar
        state: present
      delegate_to: localhost
      no_log: true
      become: false  

    - name: Copy Telco Tar File
      copy:
        src: "{{ installer_path }}/seed_data.tar"
        dest: "{{ sandbox_root }}/abinitio/cip/seed_data.tar"
        remote_src: false
        group: abinitio
      become_user: "{{ functional_user }}"

    - name: Log step
      lineinfile:
        path: "{{ log_file }}"
        line: |
          => Untar seed Data
        state: present
      delegate_to: localhost
      no_log: true
      become: false  

    - name: Untar Files
      ansible.builtin.command: "{{ installer_path }}/source_and_run.sh {{ item }}"
      with_items:
        - tar xvf seed_data.tar
      register: command_output
      become_user: "{{ functional_user }}"
      args:
        chdir: "{{ sandbox_root }}/abinitio/cip"
    
    - name: Display Status
      ansible.builtin.debug:
        var: command_output

    - name: Log step
      lineinfile:
        path: "{{ log_file }}"
        line: |
          => Importing Seed Data Sql in the CIP DB
        state: present
      delegate_to: localhost
      no_log: true
      become: false  

    - name: Import Seed Data SQL
      ansible.builtin.command: "{{ installer_path }}/source_and_run.sh {{ item }}"
      with_items:
        - air sandbox run ../pset/utility/import_test_database.pset -IMPORT_DB_DUMP "{{ sandbox_root }}/abinitio/cip/private_internal/xls/seed_data_20221026_131503.sql"
        - air sandbox run ../pset/subscriber_profile/sample_customer_profile_prepare.pset
        - air sandbox run ../pset/subscriber_profile/sample_customer_profile_load.pset
      register: command_output
      become_user: "{{ functional_user }}"
      args:
        chdir: "{{ sandbox_root }}/abinitio/cip/private_internal/run"

    - name: Display Status
      ansible.builtin.debug:
        var: command_output
