- name: create -env 
  hosts: cip_instance*
  become: yes # Run tasks with root privileges
  vars:
    log_file: "{{ lookup('env', 'LOG_FILE').split(',') | first}}"
    comm_config_file: "{{ lookup('env', 'CONFIG_FILE').split(',') | first}}"
    installer_path: "{{ lookup('env', 'INSTALLER_PATH').split(',') | first}}"

  tasks:

    - name: Load Global parameters
      include_vars:
        file: "{{ item }}"
      with_items:
        - "{{ installer_path }}/cip_setup_automation.yml"
        - "{{ installer_path }}/installer-versions.yml"
        - ./config-params.yml
        - "{{ comm_config_file }}"

    - name: Run create env and queue job
      ansible.builtin.command: "{{ installer_path }}/source_and_run.sh {{ item }}"
      with_items:
        - air sandbox run ../pset/utility/create_environment/create_environment.pset
      register: command_output
      become_user: "{{ functional_user }}"
      args:
        chdir: "{{ sandbox_root }}/abinitio/cip/private_internal/run"

    - name: Run adhoc job to create campaign_criteria lookup
      ansible.builtin.command: "{{ installer_path }}/source_and_run.sh {{ item }}"
      with_items:
        - air sandbox run ../pset/event_engine/utility/write_campaign_criteria_package.pset
      register: command_output
      become_user: "{{ functional_user }}"
      args:
        chdir: "{{ sandbox_root }}/abinitio/cip/private_internal/run"

    - name: Display Status
      ansible.builtin.debug:
        var: command_output
