- name: print variables
  debug:
    var: "{{ input }}"
  with_items:
    - host
    - config
  loop_control:
        loop_var: input
  
  tasks:

    - name: Load Global parameters
      include_vars:
        file: "{{ item }}"
      with_items:
        - "{{ installer_path }}/cip_setup_automation.yml"
        - ../CIP/config-params.yml
        - ../QueryIT/config-params.yml
        - ./subsystem_mapping.yml
        - "{{ comm_config_file }}"

  - name: Write dev Config
      copy:
        dest: dev.pset
        content: |
              !base||||.project.pset
              AI_REL_LOC:sandbox@ABENV||||/abinitio/cip/private_internal
              AI_TEST_FLAG@ABENV||||{{ functional_user }}
              Environment||||{{ sandbox_root }}/abinitio/stdenv
              CIP_COMMON_LOCAL_ENRICHMENT_LAYOUT@||||'$CIP_COMMON_LOCAL_MFS_QUEUE'
              CIP_COMMON_SEGMENTATION_MUTABLE_AB_HOME@||||'$AB_HOME'
              CIP_COMMON_LOCAL_SEGMENTATION_LAYOUT@||||{{ data_root_path }}/cip/mfs/mfs_{{ data_mfs_depth }}_way
              CIP_COMMON_ADC_CONFIG_FILE@||||{{ sandbox_root }}/abinitio/cip/private_internal/config/config.dev.props
              CIP_COMMON_CIPDB_PORT@||||{{ cip_db_port }}
              CIP_COMMON_CIPDB_DB_NAME@||||cip
              CIP_COMMON_QUERY_IT_SANDBOX@||||{{ sandbox_root }}/queryit   
              CIP_COMMON_QUERY_IT_DB_PASSWORD@||||{{ query_it_en_passwd }}
              CIP_COMMON_QUERY_IT_DB_USERNAME@||||{{ functional_user }}
              CIP_COMMON_ALL_TARGET_SERVERS@||||{{ cip_common_all_target_servers }}
              CIP_COMMON_CONTROL_SERVER@||||{{ cip_common_act_server }}		
              CIP_COMMON_ACT_SERVER@||||{{ cip_common_act_server }}		
              CIP_COMMON_AUDIT_SERVER@||||{{ cip_common_audit_server }}		
              CIP_COMMON_COLLECT_SERVER@||||{{ cip_common_collect_server }}		
              CIP_COMMON_CONTACT_POLICY_SERVER@||||{{ cip_common_contact_policy_server }}		
              CIP_COMMON_DETECT_SERVERS@||||{{ cip_common_detect_servers }}		
              CIP_COMMON_ELIGIBILITY_SERVERS@||||{{ cip_common_eligibility_servers }}		
              CIP_COMMON_ELIGIBLE_QUEUE_SERVERS@||||{{ cip_common_eligible_queue_servers }}		
              CIP_COMMON_ENRICHMENT_QUEUE_SERVERS@||||{{ cip_common_enrichment_queue_servers }}		
              CIP_COMMON_ENRICHMENT_SERVERS@||||{{ cip_common_enrichment_servers }}		
              CIP_COMMON_INBOUND_CHANNEL_QUEUE_SERVERS@||||{{ cip_common_inbound_channel_queue_servers }}		
              CIP_COMMON_REPORT_SERVER@||||{{ cip_common_audit_server }}		
              CIP_COMMON_CIPDB_HOST@||||{{ cip_common_audit_server }}		
      become: false
