- name: Generate executables.csv dynamically
  hosts: cipui
  become: yes # Run tasks with root privileges

  vars:
    installer_path: "{{ lookup('env', 'INSTALLER_PATH').split(',') | first}}"
    host_alias_content: "{{ lookup('file', '{{ installer_path }}/host_alias.txt').splitlines() }}"

  tasks:
    - name: Load CIP Config parameters
      include_vars:
        file: ./executables.yml

    - name: Load Global config parameters
      include_vars:
        file: "{{ installer_path }}/cip_setup_automation.yml"
        file: "{{ installer_path }}/cip_setup_server_config.yml"

    - name: Print logs
      debug:
         msg: "{{ item | split(' ') | first}}"
      loop: "{{ host_alias_content }}"


    - name: get server configuration
      ansible.builtin.debug:
              #msg: "{{ {{ item | split(' ') | first }}_config }}"
        msg: "{{ lookup('vars',item | split(' ') | first + '_config') }}"
      loop: "{{ host_alias_content }}"

    - name: write to inventory
      shell: echo -e "cip:\n  hosts:" > ./inventory.yml
      become_user: "{{ functional_user }}"

    - name: call another yaml
      include_tasks: parse_multiserver_config.yaml
      vars:
        host: "{{ item | split(' ') | first }}"
        host_ip: "{{ item | split(' ') | last }}"
        pem_file: "{{ lookup('vars',item | split(' ') | first + '_private_key') }}"
        config: "{{ lookup('vars',item | split(' ') | first + '_config') }}"
        counter: "{{ iteration+1 }}"
      loop: "{{ host_alias_content }}"
      loop_control:
        index_var: iteration

    - name: Print subsystem mapping
      lineinfile:
        path: subsystem_mapping.yml
        line: "{{ subsystem_mapping }}"
        state: present
        create: true
      with_items:
        - "{{ 'cip_common_all_target_servers: ' + cip_common_all_target_servers | split(',') | reject('match', '^$') | unique | join(',') }}"
        - "{{ 'cip_common_act_server: ' + cip_common_act_server | split(',') | reject('match', '^$') | unique | join(',') }}"
        - "{{ 'cip_common_audit_server: ' + cip_common_audit_server | split(',') | reject('match', '^$') | unique | join(',') }}"
        - "{{ 'cip_common_collect_server: ' + cip_common_collect_server | split(',') | reject('match', '^$') | unique | join(',') }}"
        - "{{ 'cip_common_contact_policy_server: ' + cip_common_contact_policy_server | split(',') | reject('match', '^$') | unique | join(',') }}"
        - "{{ 'cip_common_detect_servers: ' + cip_common_detect_servers | split(',') | reject('match', '^$') | unique | join(',') }}"
        - "{{ 'cip_common_eligibility_servers: ' + cip_common_eligibility_servers | split(',') | reject('match', '^$') | unique | join(',') }}"
        - "{{ 'cip_common_eligible_queue_servers: ' + cip_common_eligible_queue_servers | split(',') | reject('match', '^$') | unique | join(',') }}"
        - "{{ 'cip_common_enrichment_queue_servers: ' + cip_common_enrichment_queue_servers | split(',') | reject('match', '^$') | unique | join(',') }}"
        - "{{ 'cip_common_enrichment_servers: ' + cip_common_enrichment_servers | split(',') | reject('match', '^$') | unique | join(',') }}"
        - "{{ 'cip_common_inbound_channel_queue_servers: ' + cip_common_inbound_channel_queue_servers | split(',') | reject('match', '^$') | unique | join(',') }}"
        - "{{ 'cip_common_segmentation_server: ' + cip_common_segmentation_server | split(',') | reject('match', '^$') | unique | join(',') }}"
      loop_control:
        loop_var: subsystem_mapping
      become_user: "{{ functional_user }}"

    - name: call another yaml for base pset configuration
      include_tasks: create_base_config.yaml
      vars:
        host: "{{ item | split(' ') | first }}"
        config: "{{ lookup('vars',item | split(' ') | first + '_config') }}"
      loop: "{{ host_alias_content }}"
