Time_Service: cip-control,time_service,$AI_PSET/utility/time_service.pset,Graph
Utility: cip-control,utility,$AI_PSET/utility/utility_plan.pset,Plan
Contact_Policy: cip-control,contact_policy_subsystem,$AI_PSET/communication/contact_policy_subsystem.pset,Plan
Detect: cip-control,detect_subsystem,$AI_PSET/event_engine/detect_subsystem.pset,Plan
Fulfillment: cip-control,fulfillment_subsystem,$AI_PSET/fulfillment/fulfillment_subsystem.pset,Plan
Communication: cip-control,communication_subsystem,$AI_PSET/communication/communication_subsystem.pset,Plan
Control: cip-control,control_subsystem,$AI_PSET/control/control_plan.pset,Plan
A360_Enrichment: cip-control,enrichment_subsystem,$AI_PSET/enrichment/a360_integrated_enrichment_subsystem.pset,Plan
Enrichment: cip-control,enrichment_subsystem,$AI_PSET/enrichment/a360_enrich_events.pset,Graph
Collect_Event: cip-control,collect_event_subsystem,$AI_PSET/collect_integrate/cip/collect_event_subsystem.pset,Plan
